import EN_LANG from './en_robot.js';
const lang = {
	// 底部菜单栏
	tabs: ['Home', 'Markets', 'Robot', 'Profit', 'User'],
	// 首页
	home: {
		// 主页
		home: {
			useStstus: ['Trial', 'Basis', 'Advanced', 'Profession'],
			systenNotice: 'Notice',
			texts: ['Run Robot', 'profit'],
			menuListTexts: ['Invite', 'Recharge', 'Service', 'API Manage', 'Help', 'Community', 'Create Robot'],
			tabListTexts: ['Week Ranking', 'Total Ranking'],
			listHeader: ['Ranking', 'User', 'Trade Strategy', 'Earning Rate'],
			taskType: ['', 'High Trade', 'Grid Trade', 'USDT Contract']
		},
		// 机器人详情页
		robotDetail: {
			navTitle: 'Robot Details',
			titles: ['Robot Info', 'Robot Params'],
			labels: [
				'Robot ranking', 
				'Run', 
				'Total profit', 
				'Creation time', 
				'Type of play', 
				'Trade type', 
				'Pay trade quota', 
				'Sell stop ratio', 
				'Trigger cycle', 
				'Number trade',
				'Trigger price', 
				'Robot name', 
				'Trade', 
				'Channel',
			],
			unit: ['minute', 'frequency'],
			btn: 'Confirm tracking'
		},
		// API 管理页
		apiManage: {
			navTitle: 'API Manage',
			text: 'Please select the transaction channel for binding',
			btns: ['Set default', 'bind', 'delete'],
			list: ['HuoBi', 'Binance', 'Bitcoin'],
			status: ['Bind', 'Unbind', 'In use'],
			tips: [
				'Please bind the transaction channel API first',
				'Set up trading channel successfully',
				'Are you sure you want to delete the API of HuoBi exchange?', 
				'Are you sure you want to delete the API of Binance exchange?', 
				'Are you sure you want to delete the API of Bitcoin exchange?', 
				'API deleted successfully',
			]
		},
		addApi: {
			navTitles: ['HuoBi API authorize', 'Binance API authorize', 'Bitcoin API authorize'],
			navRight: 'Course',
			texts: [
				'Get the API key generated by the HuoBi account number; For synchronizing position and transaction data', 
				'Get the API key generated by the Binance account number; For synchronizing position and transaction data', 
				'Get the API key generated by the Bitcoin account number; For synchronizing position and transaction data', 
				'Enter or copy and paste your API key',
				'When creating an API, check read and transaction permissions',
				'Warm tips: click "authorized trading" to authorize this app to conduct relevant trading operations through API. We do not provide other services of the exchange and bear any asset risk. If you suspect that there is a problem with the authorization, please log in to the relevant website immediately to remove the relevant key'
			],
			btn: 'Import',
			tips: ['Please input', 'Import succeeded']
		}
	},
	// 行情
	quotations: {
		// 行情主页
		home: {
			tabs: ['Free', 'Market', 'Exchange', 'Contract', 'Hot'],
			noData: 'No data',
			listHeader: [
				'Name/Exchange', 
				'Latest price', 
				'24H Up', 
				'Name', 
				'Currency', 
				'Platform/Number', 
				'24H Turnover（CNY）', 
				'Platform/Holding', 
				'24H Holding（CNY）',
				'Platform/Holding',
				'Hot'
			],
			texts: ['', 'Value', 'Focus on high-quality digital assets with one click', 'One-click add'],
			placeholder: 'Please enter the currency code',
			btn: 'Search',
			tips: ['Please select the currency of your choice', 'One-click add optional success']
			
		},
		// 行情详情页
		detail: {
			low: 'Low',
			high: 'High',
			tabs: ['Global', 'Inflow outflow', 'Ratio', 'Currency info'],
			texts: [
				'Fund inflow', 
				'Fund outflow', 
				'Comparison of fund flow across the network', 
				'See more', 
				'See empty', 
				'Long and short power comparison of the entire network',
			],
			labels: ['Total issuance', 'Total circulation', 'Crowdfunding price', 'white paper', 'Introduction'],
			btns: ['Create task', 'Set reminder', 'Plus option', 'Cancel option'],
			tips: ['Optional added successfully', 'Successfully unselected']
		}
	},
	// 机器人
	robot: EN_LANG,
	// 用户
	user: {
		// 用户主页
		user: {
			account: 'Balances（USDT）',
			status: ['Renew', 'Open', 'Nonactivated', 'Expired'],
			time: 'Time：',
			btnTexts: ['Deposit', 'Detailed'],
			menuList: ['Bind API', 'Invite', 'Hlep', 'Group', 'Notice', 'Opinion', 'About us', 'Check for updates'],
			signOut: 'Exit'
		},
		// 用户信息页
		info: {
			navTitle: 'User Info',
			itemTexts: ['My cell phone', 'Login password', 'Sign up time', 'Status', 'Change password', 'My head', 'Change head'],
			statusTexts: ['Service not opened', 'Opened', 'Expired'],
			exitText: 'Exit the current login account?',
			exit: 'Exit',
		},
		// 修改头像页
		revise: {
			navTitle: 'Change head',
			btns: ['Photograph', 'Album selection', 'Confirm'],
			tips: ['Successfully modified the avatar']
		},
		// 关于我们页
		about: {
			navTitle: 'About us',
			appName: 'Eslacoin',
			edition: 'Version',
			text: '24-hour automatic trading arbitrage, including team mode, welcome strong customers to customize their own brand quantitative trading APP for better operation, please contact customer service for details',
			titles: [
				'Make encrypted transactions easy through the Eslacoin platform!', 
				'The 3 core principles of the Eslacoin platform!', 
				'Why choose Eslacoin!',
			],
			labels: [
				'Focus users', 
				'Cooperation', 
				'Hardcore', 
				'Upright and firm', 
				'① Provide traders with a simple and intuitive interface', 
				'② Develop advanced tools to simplify transactions', 
				'③ Maintain a reliable, trustworthy and transparent business',
			],
			texts: [
				"Our team started to build Eslacoin for our inner circle in 2017. We don't like to trade crypto directly on the exchange, because you have to constantly monitor your position to get some profit. This inspired us to build a reliable platform that can help us stabilize our earnings in the crypto field, while eliminating some emotions that may lead to losses. Once we realized the power of Eslacoin, we opened it up to the crypto world, and the rest is history.", 
				'After our launch, user feedback continued to flood in, and slowly but surely developed the platform to where it is today. As a feedback-oriented service, we always maintain and promise to be user-centric in any product developed for Eslacoin.',
				'We always put user needs in the first place and provide users with high-quality services to protect their rights and rights.',
				'We are open and honest. We are a team striving for a common goal, and we are working together to build the Binance ecosystem.',
				'We are result-oriented and aim to get things done. We are passionate and hardworking. Whenever we encounter failure, we can always learn quickly and cheer up.',
				'We are responsible for our words and deeds. When mistakes are made, corrective measures will be taken proactively. We always abide by the code of ethics. We never give up.',
				'Our first goal is to simplify and simplify the learning phase as much as possible. We should create a simple introductory process to help users get started with the interface. Start with the needs of users and think about what users think. We must remember that the user interface is always built for a specific user. This is our job. It is not just to create an interface and the required functions required by the interface, but to create an interface that the user can understand and use without having to remember or memorize anything.',
				"Our second goal is to enhance the experience and enhance functionality. We have always been focusing on digital currency quantitative investment, and using the stock futures market's years of quantitative strategy trading experience, combined with the characteristics of the digital currency market, we have transformed and upgraded trading strategies. Using cutting-edge technology, we are committed to developing new trading tools and strategies to quickly respond to the highly competitive trading market. Combining big data and machine learning algorithms for data analysis, according to the characteristics of the digital currency spot and futures markets, promote the research of existing trading and market making strategies, and continuously optimize and innovate in the exploration.",
				'We comply with privacy protection related laws and regulations, and provide customers with a stable, secure and privacy-friendly cloud environment. Based on security, compliance, privacy, resilience, and transparency, we provide you with technology, future, and trustworthy services. We perform our work in a responsible and autonomous manner to provide reliable services for the entire blockchain ecosystem.'
			],
			listLabels: [
				'Investment', 
				'Market analysis', 
				'AI Strategy', 
				'Customize', 
				'Major overall', 
				'Distribute',
			],
			listTexts: [
				'Committed to quantitative transactions for blockchain entrepreneurs to provide liquidity for the digital currency market and make prices more effective.',
				'A one-stop blockchain industry service platform that integrates industry news, information, market quotations, data, investment strategies, etc.',
				'Through big data collection and real-time transaction conditions, the system automatically configures AI recommended strategies with ultra-high profitability.',
				'According to different user needs, provide custom configuration indicators, which can be changed at any time during operation, and the robot will strictly implement it.',
				'Eslacoin trading tools will develop into production tools for the digital currency market, and investors will become increasingly professional.',
				'According to the Fibonacci sequence, multiplier sequence, average cost method and other trading mathematical prototypes, the entire strategy is reasonably allocated.'
			],
			update: ['Check for updates', 'The latest version']
		},
		// 反馈建议页
		feedBack: {
			navTitle: 'Feedback opinion',
			placeholder: 'Please enter feedback content...',
			tipsTexts: ['Please enter feedback content', 'Feedback success'],
			btnText: 'Submit'
		},
		// 联系客服页
		customer: {
			navTitle: 'Contact service',
			btn: 'Contact service',
			copy: 'Copy',
			text: 'wechat'
		},
		// 订购服务页
		buyService: {
			navTitle: 'Ordering services',
			date: ['30Days', '90Days', '180Days', '365Days'],
			btns: ['Immediate payment', 'Free to use'],
			tip: 'Payment successful',
			labels: ['Free version', 'Basic version', 'Premium version', 'Profession version'],
			text: 'USDT Payment',
			tips: ['The service cannot be lower than the current existing service', 'Free to use, no subscription required'],
			texts: [
				'Contains all the contents of the premium version',
				'Unlimited number of bound exchanges',
				'Unlimited number of robots',
				'Spot strategy robot trading is not restricted',
				'Contract strategy robot trading is not restricted',
				'Strategist qualification application',
				'Strategy documentary',
				'Include all functions of the basic version at the same time',
				'Bind to 10 exchanges',
				'30 robots',
				'Contains all features of the free version at the same time',
				'Bind to 5 exchanges',
				'10 robots',
				'Contract strategy robot (AI recommendation, custom strategy)',
				'The free version contains',
				'Bind a single exchange',
				'1 robots',
				'Spot strategy robot (AI recommendation, custom strategy)'
			]
		},
		// 资金明细页
		fundDetail: {
			navTitle: 'Funding details',
			balance: ['Balance before account change', 'Balance after account change'],
			accountType: ['Recharge', 'Withdraw', 'Commission', 'Buy service'],
			noData: 'No fund details'
		},
		// 用户充值页
		userPay: {
			navTitle: 'User recharge',
			copy: 'Copy address',
			record: 'Recharge record',
			tips: [ 'Important explain', 
					'When recharging usdt, please recharge the corresponding usdt type (TRC20 or ERC20), otherwise it will not be retrieved.',
					'When recharging usdt, it needs the confirmation of the network node. It usually takes a few minutes, sometimes several hours. After the confirmation is successful, it will automatically arrive at the account.']
		},
		// 充值记录页
		payRecord: {
			navTitle: 'Recharge record',
			address: 'Pay address',
			id: 'Transfer ID',
			noData: 'No recharge record',
			ststus: ['Received', 'Not received']
		},
		// 官方社群页
		community: {
			navTitle: 'Official Community',
			titles: ['Official Telegram', 'Official wechat group', 'Official QQ group', 'Official Echa group'],
			btn: 'Copy',
			names: ['telegram', 'Wechat', 'QQ', 'Echa']
		},
		// 公告页
		notice: {
			navTitle: 'Notice',
			noData: 'No notice'
		},
		// 公告详情页
		noticeDetail: {
			navTitle: 'Notice detail',
			label: 'Respected user'
		}
		
	},
	// 收益
	profit: {
		// 收益主页
		home: {
			assets: ['Total assets', 'Spot assets', 'Contract assets'],
			statistics: ['Income statistics', 'Cumulative income', 'Today income', 'single'],
			chart: ['Yield curve graph', 'Day', 'Week'],
			tip: 'Income',
			noApi: 'Unbound API',
			bindApi: 'No data please bind API',
			invalid: 'API is invalid'
		}
	},
	// 帮助教程
	help: {
		// 帮助教程主页
		home: {
			navTitle: "Help tutorial",
			menus: [
				'Software APP Frequently Asked Questions', 
				'Software APP use help', 
				'Huobi API Adding Tutorial', 
				'Binance API Adding Tutorial',
				'The profit principle and use method of high frequency trading', 
				'The profit principle and use method of grid trading', 
				'The profit principle and usage method of contract "grid trading"', 
				'The profit principle and usage method of contract "smart long and short"',
			]
		},
		// APP常见问题页
		question: {
			navTitle: "APP FAQ",
			list: [
				' What is the principle of how the APP trading system is profitable？', 
				'How much USDT can be traded at the minimum？', 
				'Will it automatically buy and sell？', 
				'Support those trading platforms？', 
				'How to activate the service?', 
				'Are my digital assets safe?', 
				'How to invite others to use and invite revenue?',
			],
			texts: [
				'Answer: The trading system launched by Eslacoin, "High-frequency trading, grid trading, smart long and short, contract grid. After our 4 years of testing, it can be long-term stable and profitable. In 90% of the market fluctuations Profits can be achieved in both China, and fully automated quantitative transactions that cannot be achieved by humans can be realized.',
				'Answer: 10USDT, you can trade, the average monthly rate of return is 30%-50%.',
				'Answer: Yes, the fully automatic currency speculation opportunity automatically executes buying, selling, replenishment and profit taking, and a series of trading operations.',
				'Answer: Currently, Binance, Huobi, and Bitcoin are supported.',
				'Answer: Directly in APP-My-click on the account balance-open service-and then follow the interface information to purchase the service you need. You can also consult our online customers for help.',
				'Answer: Your currency is on the exchange, and the API can only open the read and transaction permissions. Without the permission to withdraw the currency, your currency is very safe.',
				'Answer: Direct promotion commission is 30%, indirect promotion commission is 10%, and the best team commission is 20%. You can enter APP-My-Invite-Enter my team interface-click the invitation poster-the system will generate an invitation poster, and send it to a friend to complete the promotion. When the reward reaches a certain amount, you can also apply for withdrawal on the invitation interface. While gaining investment income, you can also get invitation rewards to kill two birds with one stone.'
			],
			tips: [
				'For details, please refer to: Principles and Instructions of High Frequency Trading and Principles and Instructions of Grid Trading',
				'For details, please refer to: APP Instructions-Opening Service'
			]
		},
		// APP使用帮助
		use: {
			navTitle: 'APP use help',
			titles: ['One. How to recharge', 'Two. How to activate the service', 'Three. How to bind API'],
			texts: [
				'Find the top-up interface', 
				'Check-in APP-click on mine (Figure 1). Click to deposit coins (Figure 2).',
				'Copy the recharge address to complete the recharge.',
				'After entering the recharge interface, we copy the recharge address, and then go to the exchange or wallet to transfer USDT to the address just copied to complete the transfer. As follows (Figure 3).',
				'Open mine, click to activate service',
				'Click to open in APP-My-Account Balance. Then click the enable button (Figure 3 below).',
				'Choose the type of service and complete the activation',
				'Enter the ordering service interface, select the type of service according to your needs, and click Pay to complete the activation.',
				'For details, please refer to: Huobi API Adding Tutorial/Binance API Adding Tutorial'
			]
		},
		// 高频/网格交易说明
		explain: {
			navTitles: ['High trading explain', 'Grid trading explain'],
			gpTitles: [
				'One.The profit principle of high-frequency trading', 
				'Two.Instructions for the use of high-frequency trading',
			],
			gpTexts: [
				'What is high frequency trading',
				'High-frequency trading is widely used in the futures market. In essence, it is a trading system that automatically opens positions with time as a cycle. Through high-frequency operations, stable profits are achieved, which is very suitable for volatile market conditions. Automatic position opening is triggered according to the time period, and the sell order is immediately placed after the position is successfully opened. The average price of the sell order = the average price of the buy order * (1 + the take profit ratio of the sell order).',
				'As shown in the figure below, we buy in a period of 10 minutes. In the figure below, we have completed 5 transactions within 1 hour. Each time we buy a take profit order, we will stop profit and exit once the price is reached. We will not buy when it exceeds the range we set.',
				'What are the advantages of high-frequency trading.',
				'One is that high-frequency trading can quickly make profits in the market, and its transaction speed and rhythm cannot be completed manually, which truly realizes quantitative trading. The second is to use a time period to open a position, to a large extent, to avoid the high cost of the position and the high level of lockup. Third, interval trading and sub-warehouse trading, while averaging costs, control risks to a great extent.',
				'Go to the home page and click Create Robot.',
				'You can choose the default robot to create.',
				'We provide you with three different types of default robots for you to choose from',
				'You can choose custom parameters to create a robot.',
				'You can customize the task and click Create Task after completion. If you are not familiar with the parameters, you can click the question mark behind each parameter to view it.',
				'The created robot will be displayed on the robot homepage.',
				'The created robot will be displayed here, and you can edit and operate the created task.',
				'You can also view the information of each transaction in the robot details.',
				'You can perform operations on this task in the transaction record, and you can view all your transaction information.',
				'The operation of the high-frequency trading system is simple and convenient. If you have any questions, please consult our online customer service.'
			],
			wgTitles: ['One.The profit principle of grid trading', 'Two.Instructions for using grid trading'],
			wgTexts: [
				'What is grid trading',
				'Grid trading originated in the foreign exchange market. In the past 4 years, we have optimized and tested this trading system. In 80% of the active currencies, 95% of the market fluctuations can achieve long-term sustainable and stable profitability.',
				'95% of the price of any investment product will fluctuate back and forth within a specific range in a short period of time. In essence, the strategy is to use the short-term price range, in this price range, sell high and buy low to achieve profitability, when the price is not in this range, we stop buying (the strategy logic diagram below).',
				'What are the advantages of grid trading.',
				'One is to prevent investors from chasing ups and downs. The second is to stop profit after gaining profit and proceed to the next order operation (the profit percentage in the system can be set by yourself, and we recommend using a smaller percentage). The third is to avoid buying a quilt cover at a higher position. Fourth, the cost of opening a position can be shared by replenishment, which makes it easy to make a profit. Fifth, fully automatic quantitative trading, completely free your hands, and at the same time intelligent trading, buying and selling must be one step faster.',
				'Go to the home page and click Create Robot.',
				'You can choose the default robot to create.',
				'We provide you with three different types of default robots for you to choose from',
				'You can choose custom parameters to create a robot.',
				'You can customize the task and click Create Task after completion. If you are not familiar with the parameters, you can click the question mark behind each parameter to view it.',
				'The created robot will be displayed on the robot homepage.',
				'The created robot will be displayed here, and you can edit and operate the created task.',
				'You can also view the information of each transaction in the robot details.',
				'You can perform operations on this task in the transaction record, and you can view all your transaction information.',
				'The operation of the grid trading system is simple and convenient. If you have any questions, please consult our online customer service.'
			],
		},
		// API添加教程页
		course: {
			navTitle: 'API add tutorial',
			titles: [
				'Click to Login',
				'Find API management',
				'Create API',
				'Complete security verification',
				'Complete binding'
			],
			hbTitles: 'Log in to Huobi website',
			baTitles: 'Log in to Binance website',
			hbTexts: [
				'Visit in browser',
				'or',
				'(For the latest website, please consult the official exchange customer service).',
				'Click the login button in the upper left corner to log in to your Huobi account',
				'Place the mouse on the avatar icon of the villain and click "API Management"',
				'Bind IP: () Please contact customer service (WeChat: qzdcbj), without binding IP, the validity period is only 3 months',
				'Created successfully, copy it to the "API Management-Huobi API Authorization" of the fully automatic coin machine APP, paste the Access Key, Secret Key, and complete the binding.'
			],
			baTexts: [
				'Visit in browser',
				'(For the latest website, please consult the official exchange customer service).',
				'Click the login button in the upper left corner to log in to your Binance account',
				'Place the mouse on the avatar icon of the villain and click "API Management"',
				'Add a name to the API key, such as "Fully Automatic Coin Scrambler".',
				'Obtain the verification code and complete the security verification.',
				'The creation is successful, copy it to the "API Management-Binance API Authorization" of the fully automatic coin machine APP, paste the Access Key, Secret Key, and complete the binding.'
			]
		},
		// 合约说明页
		contract: {
			navTitles: ['Contract-grid trade explain', 'Smart long and short explain'],
			znTitles: [
				'One.The profit principle of USDT perpetual contract smart long and short', 
				'Two.Instructions for Smart Long and Short'],
			znTexts: [
				'What is smart long and short.',
				'Smart Long Short is a short-term contract trading system. Calculate the latest 5-minute market trends according to trading channels, quickly analyze the current data through AI intelligence, and get the price trend direction, so as to make a bullish and bearish (bearish and bearish) judgment.',
				'The data that Smart Long and Short will analyze include: the peak value of the price fluctuation range, the average price, the current key resistance and support levels, the current long-term price trend direction, and other basic trading factors.',
				'The core of smart long and short lies in the calculation of key data to get the judgment of the current price trend. In order to reduce the risk during use, you can design your own stop-profit and stop-loss, or you can choose a conservative robot to serve you. With the support of data, excess returns can be achieved.',
				'What are the advantages of smart long and short.',
				'One is that using AI intelligent calculations and making decisions based on data can largely avoid irrational behavior. Second, fast trading and quick decision-making, decisive implementation of strategies, to a large extent avoid losses caused by price changes. The third is to liberate your hands and realize fully automatic trading in contract transactions. There is no need to watch the market or worry about missing key market conditions.',
				'Go to the home page and click Create Robot.',
				'You can choose the default robot to create.',
				'We provide you with three different types of default robots for you to choose from',
				'You can choose custom parameters to create a robot.',
				'You can customize the task and click Create Task after completion. If you are not familiar with the parameters, you can click the question mark behind each parameter to view it.',
				'The created robot will be displayed on the robot homepage.',
				'The created robot will be displayed here, and you can edit and view the created task.',
				'The operation of the intelligent long-short system is simple and convenient. If you have any questions, please consult our online customer service.'
			],
			wgTitles: [
				'One.The profit principle of contract grid trading', 
				'Two.Instructions for using grid trading',
			],
			wgTexts: [
				'What is contract grid trading',
				'Contract grid trading is a derivative system of spot grid trading. Its trading principle is similar to that of spot grids. It also uses a short-term price range in which to sell high and buy low to achieve profitability. The only difference is that there is a position opening mode. The difference,',
				'As shown in the figure below, we assume that we have entered the market with a bearish view: set a price range (between the red lines) and divide the price range into several parts. Each price interval is equal to form a grid. When the price reaches the grid line, a position is opened. , And each grid will only open a position once (except for the stop-profit or stop-loss). Note that the stop-profit and stop-loss here can be set by yourself or use the system default.',
				'What are the advantages of contract grid trading.',
				'One is that no matter whether you choose the right direction in contract trading, when you use grid trading, you can avoid serious losses to a large extent. The second is that in the case of frequent price fluctuations, it can also bring huge returns. The third is, fully automatic quantitative trading, completely free your hands, and at the same time intelligent trading, buying and selling must be one step faster.',
				'Go to the home page and click Create Robot.',
				'You can choose the default robot to create.',
				'We provide you with three different types of default robots for you to choose from',
				'You can choose custom parameters to create a robot.',
				'You can customize the task and click Create Task after completion. If you are not familiar with the parameters, you can click the question mark behind each parameter to view it.',
				'The created robot will be displayed on the robot homepage.',
				'The created robot will be displayed here, and you can edit and operate the created task.',
				'The operation of the contract grid trading system is simple and convenient. If you have any questions, please consult our online customer service.'
			],
		}
	},
	// 邀请
	invite: {
		// 邀请主ye
		home: {
			navTitle: 'Invite to make money',
			labels: ['Your level', 'Invitation code', 'Your commission', 'Today commission', 'Total commissio'],
			btns: ['Invitation poster', 'Check details', 'Apply withdrawal'],
			titles: ['Direct push', 'Team'],
			noData: 'No invitation'
		},
		// 邀请海报页
		poster: {
			navTitle: 'Invitation poster',
			code: 'Invitation code',
			btn: 'save into the album',
			text: 'After saving the picture, share it with more people and get commission!'
		},
		// 佣金明细页
		commission: {
			navTitle: 'Commission details',
			noData: 'No commission details',
			labels: ['User', 'Reward', 'Time']
		},
		// 申请提币页
		exchange: {
			navTitle: 'Apply for withdrawal',
			labels: [
				'Withdrawal address type', 
				'Withdrawal address', 
				'Number of withdrawals', 
				'Handling fee', 
				'Verification code',
			],
			code: ['get verification code', 'Get it later'],
			btns: ['submit application', 'Withdrawal details'],
			placeholder: [
				'Enter or long press to paste the address', 
				'The minimum withdrawal amount is 100', 
				'Please enter verification code',
			],
			tips: [
				'Please enter the withdrawal address', 
				'Please enter the correct withdrawal address', 
				'Please enter the withdrawal quantity', 
				'The number of withdrawals cannot be less than 100', 
				'Verification code sent successfully', 
				'Application for withdrawal is successful',
			]
		},
		// 提币明细页
		extractDetail: {
			navTitle: 'Withdrawal details',
			labels: ['Amounts', 'Status', 'Address type', 'application time', 'Withdrawal address', 'Checking order'],
			status: ['completed', 'Has been sent', 'under review'],
			noData: 'No withdrawal details',
		}
	},
	// 登录注册页
	login: {
		// 登录页
		login: {
			placeholder: ['Mobile phone number', 'Login password'],
			btns: ['Forget the password', 'Sign in', 'Sign up'],
			text: 'Eslacoin Forerunner of quantitative trading'
		},
		// 忘记密码
		forget: {
			navTitle: 'Forgot password',
			btns: ['Change password', 'Get VER code'],
			tips: ['Password changed successfully', 'Send successful']
		},
		// 注册页
		register: {
			navTitle: 'Sign up',
			texts: ['Agree', 'User agreement'],
			btn: 'Sign up',
			tips: ['Please read and check the user agreement first', 'Sign up was successful']
		},
		// 免责条款/用户协议
		agreement: {
			navTitle: 'Escape Clause',
		}
	},
	// 引导页
	guide: {
		titles: [
			'Digital currency quantitative investment', 
			'Smart AI trading',
			 'Safe and reliable',
			],
		texts: [
			'Global mainstream digital asset trading platform, multi-dimensional big data intelligent analysis of market conditions, 24-hour network monitoring', 
			'One-click to start the quantitative trading system, free hands in the whole process, real custody', 
			'Intelligent AI cloud big data real-time analysis of the market, real-time intelligent computing to adjust the supplementary strategy, safe and reliable',
		],
		btn: 'Experience'
	},
	// 公共文字配置
	common: {
		cancel: 'Cancel',
		confirm: 'Confirm',
		date: ['Today', '7 Days', '30 Days', 'Yesterday'],
		tips: [
			'Please input mobile phone number', 
			'Please enter the correct mobile phone number', 
			'Please input a password', 
			'The password is a combination of 6-12 alphanumeric characters', 
			'Please enter the verification code', 
			'Please enter the correct verification code', 
			'Verification code sent successfully',
		],
		labels: ['Password', 'Code'],
		btns: ['Get VER code', 'Get it later', '短信发送中'],
		placeholder: [
			'Mobile phone number', 
			'6-12 digit alphabet', 
			'Verification code', 
			'Invitation code', 
		],
		texts: ['M', 'B', 'MB'],
		times: ['Minute', 'Hour', 'Day', 'Week', 'Month', 'seconds'],
		money: ['M', 'B', 'MB'],
		unit: ['Pieces']
	}
}

export default lang;